"""MCP server exposing the Motion Energy budget."""

from __future__ import annotations

import asyncio
import logging
import socket
import threading
import time
from typing import Annotated, Literal

import uvicorn
from mcp.server import MCPServer
from mcp.server.transport_security import TransportSecuritySettings
from mcp.types import ToolAnnotations
from pydantic import Field

from taprivo.config import Config
from taprivo.core.energy import EnergyEngine, SpendRequest
from taprivo.mcp.schemas import EnergyOut, LastSpendOut, SessionOut, SpendOut, StatsOut
from taprivo.mcp.security import ASGIApp, LocalGuardMiddleware

TOOL_NAMES = ("get_energy", "spend_energy", "get_stats", "get_session")

INSTRUCTIONS = (
    "Taprivo exposes an optional, gamified Motion Energy budget generated by the user's "
    "finger taps. It is not a token balance and not permission to start unrelated work. "
    "Read get_energy before a substantial implementation burst and call spend_energy once "
    "with a short reason, a unique request_id and the current session_id. Reuse the same "
    "request_id when retrying."
)


def build_server(engine: EnergyEngine, config: Config) -> MCPServer:
    mcp = MCPServer("Taprivo", instructions=INSTRUCTIONS)
    started = time.monotonic()
    read_only = ToolAnnotations(read_only_hint=True, open_world_hint=False)

    @mcp.tool(title="Get Motion Energy", annotations=read_only)
    def get_energy() -> EnergyOut:
        """Current Motion Energy balance for this session."""
        engine.mark_tool_call()
        s = engine.snapshot()
        return EnergyOut(
            session_id=s.session_id,
            available=s.available,
            generated=s.gross_generated,
            overflow=s.overflow,
            spent=s.spent,
            max_energy=s.max_energy,
            tracking=s.tracking,
        )

    @mcp.tool(
        title="Spend Motion Energy",
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    def spend_energy(
        amount: Annotated[int, Field(description="Whole energy units to spend; must be > 0.")],
        reason: Annotated[str, Field(description="Short reason shown to the user.")],
        request_id: Annotated[
            str,
            Field(
                min_length=1,
                max_length=128,
                description="Client-generated unique id; reuse on retry.",
            ),
        ],
        session_id: Annotated[
            str,
            Field(min_length=1, max_length=64, description="Session id from get_energy."),
        ],
        project_id: Annotated[
            str | None,
            Field(max_length=128, description="Optional local project alias."),
        ] = None,
    ) -> SpendOut:
        """Deduct energy from the shared balance.

        Returns success=false with an error code instead of raising.
        """
        engine.mark_tool_call()
        result = engine.spend(
            SpendRequest(
                amount=amount,
                reason=reason,
                request_id=request_id,
                session_id=session_id,
                project_id=project_id,
            )
        )
        return SpendOut(
            success=result.success,
            session_id=result.session_id,
            spent=result.spent,
            remaining=result.remaining,
            transaction_id=result.transaction_id,
            error=result.error.value if result.error else None,
            available=result.available,
        )

    @mcp.tool(title="Get session stats", annotations=read_only)
    def get_stats(scope: Literal["session"] = "session") -> StatsOut:
        """Tap and spend statistics for the current session."""
        engine.mark_tool_call()
        s = engine.snapshot()
        last = (
            LastSpendOut(
                amount=s.last_spend.amount,
                reason=s.last_spend.reason,
                at_utc=s.last_spend.at_utc.isoformat(),
            )
            if s.last_spend
            else None
        )
        return StatsOut(
            session_id=s.session_id,
            taps_total=s.taps_total,
            taps_per_finger={finger.value: count for finger, count in s.taps_per_finger.items()},
            taps_per_minute=s.taps_per_minute,
            combo=s.combo,
            spend_count=s.spend_count,
            last_spend=last,
            session_duration_seconds=s.session_duration_seconds,
        )

    @mcp.tool(title="Get session", annotations=read_only)
    def get_session() -> SessionOut:
        """Session identity and connection health."""
        engine.mark_tool_call()
        s = engine.snapshot()
        return SessionOut(
            session_id=s.session_id,
            started_at_utc=s.started_at_utc.isoformat(),
            mode=s.mode,
            tracking=s.tracking,
            mcp_uptime_seconds=int(time.monotonic() - started),
            last_tool_call_utc=s.last_tool_call_utc.isoformat() if s.last_tool_call_utc else None,
        )

    return mcp


log = logging.getLogger(__name__)

MAX_BODY_BYTES = 65536


def build_asgi_app(engine: EnergyEngine, config: Config, token: str) -> ASGIApp:
    port = config.server.port
    hosts = {f"127.0.0.1:{port}", f"localhost:{port}"}
    origins = {f"http://127.0.0.1:{port}", f"http://localhost:{port}"}
    mcp = build_server(engine, config)
    inner = mcp.streamable_http_app(
        stateless_http=True,
        host=config.server.host,
        max_request_body_size=MAX_BODY_BYTES,
        transport_security=TransportSecuritySettings(
            enable_dns_rebinding_protection=True,
            allowed_hosts=sorted(hosts),
            allowed_origins=sorted(origins),
        ),
    )
    return LocalGuardMiddleware(
        inner,
        token=token,
        allowed_hosts=hosts,
        allowed_origins=origins,
        rate_per_second=config.server.rate_limit_per_second,
        max_body_bytes=MAX_BODY_BYTES,
    )


def port_is_free(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind((host, port))
        except OSError:
            return False
    return True


class McpServerThread(threading.Thread):
    """Runs the loopback MCP server on its own asyncio loop."""

    def __init__(self, engine: EnergyEngine, config: Config, token: str) -> None:
        super().__init__(name="taprivo-mcp", daemon=True)
        self._engine = engine
        self._config = config
        self._token = token
        self._server: uvicorn.Server | None = None
        self._ready = threading.Event()

    def run(self) -> None:
        host, port = self._config.server.host, self._config.server.port
        if not port_is_free(host, port):
            self._engine.set_mcp_status(
                "error",
                f"port {port} is already in use; set server.port in config.yaml and re-run "
                "'taprivo setup claude'",
            )
            self._ready.set()
            return
        app = build_asgi_app(self._engine, self._config, self._token)
        self._server = uvicorn.Server(
            uvicorn.Config(
                app, host=host, port=port, log_level="warning", access_log=False, lifespan="on"
            )
        )
        try:
            asyncio.run(self._serve())
        except Exception as exc:  # pragma: no cover - defensive
            log.exception("MCP server crashed")
            self._engine.set_mcp_status("error", str(exc))
            self._ready.set()

    async def _serve(self) -> None:
        assert self._server is not None
        task = asyncio.create_task(self._server.serve())
        while not self._server.started and not task.done():
            await asyncio.sleep(0.02)
        if task.done() and task.exception() is not None:
            self._engine.set_mcp_status("error", str(task.exception()))
        else:
            self._engine.set_mcp_status("ready")
            log.info("MCP ready on %s", self._config.endpoint_url)
        self._ready.set()
        await task

    def wait_ready(self, timeout: float = 5.0) -> bool:
        return self._ready.wait(timeout)

    def stop(self, timeout: float = 5.0) -> None:
        # Bound the wait for `run()` to reach the point where `self._server`
        # is assigned (or exit early on a port-in-use error) before deciding
        # whether there is a server to signal. Calling stop() immediately
        # after start(), before the thread has been scheduled, would
        # otherwise silently skip should_exit and just time out on join().
        self._ready.wait(timeout)
        if self._server is not None:
            self._server.should_exit = True
        self.join(timeout)
