"""MCP server exposing the Motion Energy budget."""

from __future__ import annotations

import time
from typing import Annotated, Literal

from mcp.server import MCPServer
from mcp.types import ToolAnnotations
from pydantic import Field

from taprivo.config import Config
from taprivo.core.energy import EnergyEngine, SpendRequest
from taprivo.mcp.schemas import EnergyOut, LastSpendOut, SessionOut, SpendOut, StatsOut

TOOL_NAMES = ("get_energy", "spend_energy", "get_stats", "get_session")

INSTRUCTIONS = (
    "Taprivo exposes an optional, gamified Motion Energy budget generated by the user's "
    "finger taps. It is not a token balance and not permission to start unrelated work. "
    "Read get_energy before a substantial implementation burst and call spend_energy once "
    "with a short reason, a unique request_id and the current session_id. Reuse the same "
    "request_id when retrying."
)


def build_server(engine: EnergyEngine, config: Config) -> MCPServer:
    mcp = MCPServer("Taprivo", instructions=INSTRUCTIONS)
    started = time.monotonic()
    read_only = ToolAnnotations(read_only_hint=True, open_world_hint=False)

    @mcp.tool(title="Get Motion Energy", annotations=read_only)
    def get_energy() -> EnergyOut:
        """Current Motion Energy balance for this session."""
        engine.mark_tool_call()
        s = engine.snapshot()
        return EnergyOut(
            session_id=s.session_id,
            available=s.available,
            generated=s.gross_generated,
            overflow=s.overflow,
            spent=s.spent,
            max_energy=s.max_energy,
            tracking=s.tracking,
        )

    @mcp.tool(
        title="Spend Motion Energy",
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    def spend_energy(
        amount: Annotated[int, Field(description="Whole energy units to spend; must be > 0.")],
        reason: Annotated[str, Field(description="Short reason shown to the user.")],
        request_id: Annotated[
            str,
            Field(
                min_length=1,
                max_length=128,
                description="Client-generated unique id; reuse on retry.",
            ),
        ],
        session_id: Annotated[
            str,
            Field(min_length=1, max_length=64, description="Session id from get_energy."),
        ],
        project_id: Annotated[
            str | None,
            Field(max_length=128, description="Optional local project alias."),
        ] = None,
    ) -> SpendOut:
        """Deduct energy from the shared balance.

        Returns success=false with an error code instead of raising.
        """
        engine.mark_tool_call()
        result = engine.spend(
            SpendRequest(
                amount=amount,
                reason=reason,
                request_id=request_id,
                session_id=session_id,
                project_id=project_id,
            )
        )
        return SpendOut(
            success=result.success,
            session_id=result.session_id,
            spent=result.spent,
            remaining=result.remaining,
            transaction_id=result.transaction_id,
            error=result.error.value if result.error else None,
            available=result.available,
        )

    @mcp.tool(title="Get session stats", annotations=read_only)
    def get_stats(scope: Literal["session"] = "session") -> StatsOut:
        """Tap and spend statistics for the current session."""
        engine.mark_tool_call()
        s = engine.snapshot()
        last = (
            LastSpendOut(
                amount=s.last_spend.amount,
                reason=s.last_spend.reason,
                at_utc=s.last_spend.at_utc.isoformat(),
            )
            if s.last_spend
            else None
        )
        return StatsOut(
            session_id=s.session_id,
            taps_total=s.taps_total,
            taps_per_finger={finger.value: count for finger, count in s.taps_per_finger.items()},
            taps_per_minute=s.taps_per_minute,
            combo=s.combo,
            spend_count=s.spend_count,
            last_spend=last,
            session_duration_seconds=s.session_duration_seconds,
        )

    @mcp.tool(title="Get session", annotations=read_only)
    def get_session() -> SessionOut:
        """Session identity and connection health."""
        engine.mark_tool_call()
        s = engine.snapshot()
        return SessionOut(
            session_id=s.session_id,
            started_at_utc=s.started_at_utc.isoformat(),
            mode=s.mode,
            tracking=s.tracking,
            mcp_uptime_seconds=int(time.monotonic() - started),
            last_tool_call_utc=s.last_tool_call_utc.isoformat() if s.last_tool_call_utc else None,
        )

    return mcp
